---
cache: cargo
dist: xenial
install:
  - "source ~/.cargo/env || true"
language: rust
env: NGRAPH_CPU_ENABLE=OFF
notifications:
  email:
    on_success: never
script:
  - "travis_wait cargo build --examples"
  - "cargo test"
  - "cargo run --example main"
sudo: required
